server:
  port: 8010
  compression:
    enabled: true
    #    mime-types:
    #      - application/json
    #      - application/xml
    #      - text/html
    #      - text/xml
    #      - text/plain
    min-response-size: 1
spring:
  profiles:
    include:
      - common
  application:
    name: alicloud-web
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/op_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: password
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
############################################################
# #mybatis 配置
# #
###########################################################
mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.alicloud.config.mybatis.handler.CommonEnumTypeHandler
  type-aliases-package: com.alicloud.bean  # 所有POJO类所在包路径
  #扫描mapper文件
  mapper-locations: classpath:mappings/*.xml



#logging:
#  level:
#     root: debug

##请求和响应GZIP压缩支持
feign:
  hystrix:
    enabled: true #是否开启熔断
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 4000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

#dubbo:
#  scan:
#    base-packages: com.alicloud.service.impl
#  application:
#    qos-enable: false
#  registry:
#    address: nacos://192.168.226.139:8848
#  protocol:
#    name: dubbo
#    port: ${dubbo.port:-1}
#  provider:
#    timeout: 10000
#    retries: 1
#    threads: 500

ignore:
  startWith: /user/login,/user/regist,/test,/user/getCode,/xc/executorQuartz,/quartz,/getCache

xc:
  executor:
    enabled: true #启动线程池

#dubbo:
#  scan:
#    base-packages: com.alicloud.service.impl
#  application:
#    qos-enable: false
#  registry:
#    address: nacos://192.168.226.139:8848?username=nacos&password=nacos
#  protocol:
#    name: dubbo
#    port: ${dubbo.port:20891}
#  provider:
#    timeout: 10000
#    retries: 1
#    threads: 500
jwt:
  expire: 2880
  rsa-secret: ali-cloud-service-password
logging:
  level:
    root: info
    com.alicloud.mapper: debug
result:
  code: 203
  message: 本地配置文件覆盖成功。
  success: true