server:
  port: 8010
  compression:
    enabled: true
    #    mime-types:
    #      - application/json
    #      - application/xml
    #      - text/html
    #      - text/xml
    #      - text/plain
    min-response-size: 1
#logging:
#  level:
#     root: debug
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.226.138:8848
        group: ${NACOS_GROUP:DEFAULT_GROUP}

##请求和响应GZIP压缩支持
feign:
  hystrix:
    enabled: true #是否开启熔断
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 4000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试


ignore:
  startWith: /user/login,/user/regist,/test,/user/getCode,/xc/executorQuartz,/quartz,/getCache

xc:
  executor:
    enabled: true #启动线程池


result:
  code: 203
  message: 本地配置文件覆盖成功。
  success: true